stages:
  - Webapp build
  - Webapp test
  - Firebase deploy

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn

Webapp Build:
  image: node:16.3.0
  stage: Webapp build
  needs: []
  script:
    - cd swap
    - yarn install
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn add @mui/material @emotion/react @emotion/styled
    - yarn build
  retry: 1

ESLint:
  image: node
  stage: Webapp test
  script:
    - yarn add eslint-plugin-react@latest --save-dev
    - cd swap
    - yarn install
    - node_modules/eslint/bin/eslint.js .

Prettier:
  image: node:16.3.0
  stage: Webapp test
  needs: []
  script:
    - cd swap
    - npx prettier --check .
  retry: 1

Firebase:
  image: node:16.3.0
  stage: Firebase deploy
  before_script:
    - yarn global add firebase-tools
  script:
    - cd swap/functions
    - yarn install
    - cd ..
    - firebase use default
    - firebase deploy --only functions --token $FIREBASE_TOKEN
  