stages:
  - Build
  - Lint
  - Deploy

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn

Yarn build:
  image: node:16.3.0
  stage: Build
  needs: []
  script:
    - cd swap
    - yarn install
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn add @mui/material @emotion/react @emotion/styled
    - yarn build
  retry: 1

ESLint:
  image: node
  stage: Lint
  script:
    - yarn add eslint-plugin-react@latest --save-dev
    - cd swap
    - yarn install
    - node_modules/eslint/bin/eslint.js .

Prettier:
  image: node:16.3.0
  stage: Lint
  needs: []
  script:
    - cd swap
    - npx prettier --check .
  retry: 1

Firebase:
  image: node:16.3.0
  stage: Deploy
  before_script:
    - yarn global add firebase-tools
  script:
    - cd swap/functions
    - yarn install
    - cd ..
    - yarn build
    - firebase use default
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  