stages:
  - test
  - Deploy

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn

Yarn build:
  image: node:16.3.0
  stage: test
  script:
    - cd swap
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

ESLint:
  image: node
  stage: test
  needs: []
  script:
    - cd swap
    - yarn install --frozen-lockfile --cache-folder .yarn
    - node_modules/eslint/bin/eslint.js .

Prettier:
  image: node:16.3.0
  stage: test
  needs: []
  script:
  - cd swap
  - npx prettier --check .
  retry: 1

Cypress:
  image: cypress/base:16.3.0
  stage: test
  needs: []
  allow_failure: true
  script:
    - cd swap
    - yarn add cypress --dev
    - yarn
    - yarn start & yarn run cypress run
    - yarn nyc report --reporter=text-summary
    #- yarn nyc --reporter text mocha
    - yarn nyc report --reporter=cobertura
  retry: 1
  artifacts:
    when: always
    paths:
      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/swap/cypress/videos/**/*.mp4
      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/swap/cypress/screenshots/**/*.png
      - $CI_BUILDS_DIR/$CI_PROJECT_PATH/swap/coverage/*
    reports:
      cobertura: $CI_BUILDS_DIR/$CI_PROJECT_PATH/swap/coverage/cobertura-coverage.xml

Firebase:
  image: node:16.3.0
  stage: Deploy
  needs: [Yarn build, Prettier, ESLint]
  before_script:
    - yarn global add firebase-tools
  script:
    - cd swap
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
    - firebase use default
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    refs:
      - main

#variables:
#  a11y_urls: "https://swap-93d9f.web.app"

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  #- template: "Verify/Accessibility.gitlab-ci.yml"
    artifacts:
      name: sast
      paths:
        - gl-sast-report.json
      reports:
        sast: gl-sast-report.json
    when: always

